repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types: [text]
  - repo: local
    hooks:
      - id: make-config
        name: make config
        entry: make config
        language: system
        always_run: true
        files: "core/common/config.asm"
      - id: make-consts
        name: make consts
        entry: make consts
        language: system
        always_run: true
        files: "tracker/constants.hpp tracker/sizes.hpp tracker/maps/offsets.hpp"
      - id: nasmfmt-hook
        name: nasmfmt formatting
        entry: nasmfmt
        language: system
        files: \.asm$
        types: [text]
        args:
          [
            "-ii", "4",
            "-ci", "30"
          ]
  - repo: https://github.com/timothycrosley/isort
    rev: 6.0.1
    hooks:
      - id: isort
        language_version: python3
        args: [
          "--profile", "black",
          "-l", "120"
        ]
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [
          "--line-length", "120"
        ]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
      - id: clang-format
        args: ["-style=file"]