repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        types: [text]
  - repo: local
    hooks:
      - id: make-config
        name: Run make config
        entry: make config
        language: system
        always_run: true
        files: "src/config.asm"
      - id: nasmfmt-hook
        name: nasmfmt formatting
        entry: nasmfmt
        language: system
        files: \.asm$
        types: [text]
        args:
          [
            "-ii", "4",
            "-ci", "30"
          ]
