repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        types: [text]
  - repo: local
    hooks:
      - id: make-config
        name: Run make config
        entry: make config
        language: system
        always_run: true
        files: "src/config.asm"
      - id: make-song
        name: Run make song
        entry: make song
        language: system
        always_run: true
        files: "src/song.asm"
      - id: nasmfmt-hook
        name: nasmfmt formatting
        entry: nasmfmt
        language: system
        files: \.asm$
        types: [text]
        args:
          [
            "-ii", "4",
            "-ci", "30"
          ]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
        args: [
          "--profile", "black",
          "-l", "120"
        ]
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args: [
          "--line-length", "120"
        ]
