repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: nasmfmt-hook
        name: nasmfmt formatting
        entry: nasmfmt
        language: system
        types: [asm]
        args:
          [
            "-ii 4",
            "-ci 30"
          ]
