; File automatically generated by config.py
    %define PRECALCULATE 0

    %define TABLE_SIZE 1024
    %define ANGLE_CONSTANT __float32__(0.006135923151542565)

    %define DIRECT_MODE 0
    %define SB_BUFFER_SIZE 1024
    %define SB_EXACT_SAMPLE_RATE 0
    %define SB_BASE_PORT 0x220
    %define SB_IRQ 7
    %define SB_8BIT 0
    %define SB_16BIT 1
