; Channel
    %define CHANNEL_OUTPUT 0
    %define CHANNEL_SPLITTER 4
    %define CHANNEL_OUTPUT_FLAG 8
    %define CHANNEL_ENVELOPE_INDEX 9
    %define CHANNEL_ORDER_INDEX 10
    %define CHANNEL_OSCILLATOR_INDEX 11
    %define CHANNEL_PITCH 12
    %define CHANNEL_FLAG 16
    %define CHANNEL_FRACTION 17

; Envelope
    %define ENVELOPE_BASE_VOLUME 0
    %define ENVELOPE_SUSTAIN_LEVEL 2
    %define ENVELOPE_BIAS 4
    %define ENVELOPE_ATTACK 6
    %define ENVELOPE_DECAY 8
    %define ENVELOPE_HOLD 10
    %define ENVELOPE_RELEASE 12

; Sequence
    %define SEQUENCE_NOTES 1
    %define SEQUENCE_SIZE 2

; Order
    %define ORDER_SEQUENCES 1

; Wavetable
    %define WAVETABLE_SIZE 1
    %define WAVETABLE_DATA 2

; Oscillators
    %define OSCILLATOR_INDEX 1

; Square wave
    %define OSCILLATOR_SQUARE_DUTY_CYCLE 2

; Saw wave
    %define OSCILLATOR_SAW_REVERSE 2

; Sine wave

; Wavetable
    %define OSCILLATOR_WAVETABLE_WAVETABLE_INDEX 2
    %define OSCILLATOR_WAVETABLE_INTERPOLATION 3

; DSP
    %define DSP_EFFECT_INDEX 1
    %define DSP_OUTPUT_FLAG 2
    %define DSP_FLAG 3
    %define DSP_OUTPUT 4
    %define DSP_SPLITTER 8

; Gainer
    %define DSP_GAINER_VOLUME 12

; Distortion
    %define DSP_DISTORTION_LEVEL 12

; Filter
    %define DSP_FILTER_FREQUENCY 12
    %define DSP_FILTER_MODE 14

; Delay
    %define DSP_DELAY_DRY 12
    %define DSP_DELAY_WET 13
    %define DSP_DELAY_FEEDBACK 14
    %define DSP_DELAY_TIME 15

; Commands
    %define COMMAND_TYPE 0
    %define COMMAND_DURATION 1
    %define COMMAND_PORTAMENTO_UP_CHANNEL 2
    %define COMMAND_PORTAMENTO_UP_VALUE 3
    %define COMMAND_PORTAMENTO_DOWN_CHANNEL 2
    %define COMMAND_PORTAMENTO_DOWN_VALUE 3
    %define COMMAND_SET_MASTER_GAINER_GAIN 2
    %define COMMAND_SET_BPM_BPM 2
    %define COMMAND_SET_DIVISION_DIVISION 2
    %define COMMAND_CHANGE_BYTE_VALUE_POINTER 2
    %define COMMAND_CHANGE_BYTE_VALUE_VALUE 4
    %define COMMAND_CHANGE_WORD_VALUE_POINTER 2
    %define COMMAND_CHANGE_WORD_VALUE_VALUE 4
    %define COMMAND_CHANGE_DWORD_VALUE_POINTER 2
    %define COMMAND_CHANGE_DWORD_VALUE_VALUE 4
    %define COMMAND_CHANGE_FLOAT_VALUE_POINTER 2
    %define COMMAND_CHANGE_FLOAT_VALUE_VALUE 4
