; Channel
    %define CHANNEL_SPLITTER 0
    %define CHANNEL_PITCH 4
    %define CHANNEL_TARGET 8
    %define CHANNEL_OUTPUT_FLAG 9
    %define CHANNEL_FLAG 10
    %define CHANNEL_ENVELOPE_INDEX 11
    %define CHANNEL_ORDER_INDEX 12
    %define CHANNEL_OSCILLATOR_INDEX 13
    %define CHANNEL_FRACTION 14

; Envelope
    %define ENVELOPE_BASE_VOLUME 0
    %define ENVELOPE_SUSTAIN_LEVEL 2
    %define ENVELOPE_BIAS 4
    %define ENVELOPE_ATTACK 6
    %define ENVELOPE_DECAY 8
    %define ENVELOPE_HOLD 10
    %define ENVELOPE_RELEASE 12

; Sequence
    %define SEQUENCE_NOTES 1
    %define SEQUENCE_SIZE 2

; Order
    %define ORDER_SEQUENCES 1

; Wavetable
    %define WAVETABLE_SIZE 1
    %define WAVETABLE_DATA 2

; Oscillators
    %define OSCILLATOR_INDEX 1

; Square wave
    %define OSCILLATOR_SQUARE_DUTY_CYCLE 2

; Saw wave
    %define OSCILLATOR_SAW_REVERSE 2

; Sine wave

; Wavetable
    %define OSCILLATOR_WAVETABLE_WAVETABLE_INDEX 2
    %define OSCILLATOR_WAVETABLE_INTERPOLATION 3

; DSP
    %define DSP_EFFECT_INDEX 1
    %define DSP_OUTPUT_FLAG 2
    %define DSP_FLAG 3
    %define DSP_SPLITTER 4
    %define DSP_TARGET 8

; Gainer
    %define DSP_GAINER_VOLUME 9

; Distortion
    %define DSP_DISTORTION_LEVEL 9

; Filter
    %define DSP_FILTER_FREQUENCY 9
    %define DSP_FILTER_MODE 11

; Delay
    %define DSP_DELAY_DRY 9
    %define DSP_DELAY_WET 10
    %define DSP_DELAY_FEEDBACK 11
    %define DSP_DELAY_TIME 12

; Commands
    %define COMMAND_INSTRUCTION 0
    %define COMMAND_DURATION 1
    %define COMMAND_PORTAMENTO_UP_CHANNEL 2
    %define COMMAND_PORTAMENTO_UP_VALUE 3
    %define COMMAND_PORTAMENTO_DOWN_CHANNEL 2
    %define COMMAND_PORTAMENTO_DOWN_VALUE 3
    %define COMMAND_SET_MASTER_GAINER_GAIN 2
    %define COMMAND_SET_BPM_BPM 2
    %define COMMAND_SET_DIVISION_DIVISION 2
    %define COMMAND_CHANGE_BYTE_VALUE_POINTER 2
    %define COMMAND_CHANGE_BYTE_VALUE_VALUE 4
    %define COMMAND_CHANGE_WORD_VALUE_POINTER 2
    %define COMMAND_CHANGE_WORD_VALUE_VALUE 4
    %define COMMAND_CHANGE_DWORD_VALUE_POINTER 2
    %define COMMAND_CHANGE_DWORD_VALUE_VALUE 4
    %define COMMAND_CHANGE_FLOAT_VALUE_POINTER 2
    %define COMMAND_CHANGE_FLOAT_VALUE_VALUE 4

; Commands sequence
    %define COMMANDS_SEQUENCE_SIZE 0
    %define COMMANDS_SEQUENCE_LENGTH 2
    %define COMMANDS_SEQUENCE_DATA 3

; Commands channel
    %define COMMANDS_CHANNEL_FLAG 0
    %define COMMANDS_CHANNEL_ORDER_INDEX 1
