#pragma once

#include <cstddef>

enum class ThemeItem : size_t {
    RowPlaying,
    RowEdited,
    RowSelected,
    RowSecondarySelected,
    RowCurrentCommand,
    RowCurrentValue,
    RowTextCurrent,
    LockButton,
    LockButtonHover,
    LockButtonActive,
    UnlockButton,
    UnlockButtonHover,
    UnlockButtonActive,
    EnvelopeAttack,
    EnvelopeDecay,
    EnvelopeSustain,
    EnvelopeRelease,
    Wavetable,
    Waveform1,
    Waveform2,
    Waveform3,
    Waveform4,
    ClipboardRecent,
    ClipboardOlder,
    ButtonPlay,
    ButtonPlayFromCurrentPosition,
    ButtonStop,
    Error,
    Secondary,
    SecondaryLight,
    SecondaryBright,
    SecondaryDark,
    Tertiary,
    TertiaryLight,
    TertiaryBright,
    TertiaryDark,
    Count
};
