    %include "core/elements/osc.asm"
    %include "core/elements/adsr.asm"
    %include "core/elements/sequence.asm"
    %include "core/elements/order.asm"
    %include "core/elements/channel.asm"
    %include "core/elements/dsp.asm"
    %include "core/elements/mixer.asm"
