#define TRACKER

// Defaults
#define DEFAULT_BPM 120
#define DEFAULT_UNIT 60
#define DEFAULT_DIVISION 4
#define DEFAULT_SAMPLE_RATE 44100
#define DEFAULT_NORMALIZER 0.5
#define DEFAULT_OUTPUT_CHANNELS 2
#define DEFAULT_OUTPUT_FLAG 0

#define DEFAULT_TITLE "Untitled"
#define DEFAULT_AUTHOR "Unknown"
#define DEFAULT_MESSAGE "Chip Sequencer by Jakim, 2025"

#define DEFAULT_EDO 12
#define DEFAULT_A4_FREQUENCY 440.0
#define DEFAULT_NOTE_DIVISOR 1.0594630943592953

#define DEFAULT_ENVELOPE_BASE_VOLUME 0x7FFF
#define DEFAULT_ENVELOPE_SUSTAIN_LEVEL 0x7FFF
#define DEFAULT_ENVELOPE_BIAS 0x0000
#define DEFAULT_ENVELOPE_ATTACK 0x333
#define DEFAULT_ENVELOPE_DECAY 0x333
#define DEFAULT_ENVELOPE_HOLD 0x666
#define DEFAULT_ENVELOPE_RELEASE 0x666

#define DEFAULT_CHANNEL_PITCH 0x02000000

#define DEFAULT_SEQUENCE_LENGTH 16

#define DEFAULT_ORDER_LENGTH 1

#define DEFAULT_OSCILLATOR_DUTY_CYCLE 0x8000

#define DEFAULT_WAVETABLE_SIZE 16

#define DEFAULT_GAINER_VOLUME 0x8000

// Notes
#define NOTES 250
#define NOTE_REST 254
#define NOTE_OFF 255

// Limits
#define MAX_OUTPUT_CHANNELS 4
#define MAX_STRING_LENGTH 64

#define MAX_ENVELOPES 32
#define MAX_SEQUENCES 64
#define MAX_ORDERS 64
#define MAX_OSCILLATORS 32
#define MAX_WAVETABLES 16
#define MAX_CHANNELS 32
#define MAX_DSPS 32
#define MAX_COMMANDS_SEQUENCES 64
#define MAX_COMMANDS_CHANNELS 32
#define MAX_TARGETS 254

#define MAX_WAVETABLE_SIZE 4094
#define MAX_ENVELOPE_TIMER_LENGTH 10
#define MAX_DSP_BUFFER_SIZE 1048576 // 10 s
#define LOG2_MAX_DSP_BUFFER_SIZE 20 // log2(1048576) = 20

#define MAX_ORDER_ITEMS 64
#define MAX_STEPS 64

#define MAX_COMMAND_COMMAND_SIZE 1
#define MAX_COMMAND_VALUE_SIZE 20

#define MAX_PORTAMENTO 65.535

// Let C = magic_constant. Each frame, an envelope timer increases by C / v.
// where v is proportional to time t belonging to the range [0, MAX_ENVELOPE_TIMER_LENGTH].
// v is 16-bit, so 0xFFFF corresponds to MAX_ENVELOPE_TIMER_LENGTH (10 s by default):
// v = 0xFFFF * t / MAX_ENVELOPE_TIMER_LENGTH
// The counter is being reset when it exceeds dividend := sample_rate << 14.
// Since there are t * sample_rate frames, the equation is:
// C / v * sample_rate * t = dividend
// which simplifies to:
#define MAGIC_CONSTANT (0xFFFF << 14) / MAX_ENVELOPE_TIMER_LENGTH

// Phases
#define PHASE_ATTACK 0
#define PHASE_DECAY 1
#define PHASE_HOLD 2
#define PHASE_RELEASE 3
#define PHASE_NOTE_CUT 4

// Special order values
#define CONSTANT_ORDER 255

// Channel output masks
#define MASK_OPERATION 0b11000000
#define MASK_OPERATION_ADD 0b01000000
#define MASK_OPERATION_MULTIPLY 0b10000000
#define MASK_VARIABLE_TYPE 0b00110000
#define MASK_VARIABLE_BYTE 0b00010000
#define MASK_VARIABLE_WORD 0b00100000
#define MASK_SHIFT 0b00001111

// Channel/DSP flags
#define FLAG_BYPASS 0b00000001
#define FLAG_SPLITTER 0b00000010
#define FLAG_SYNC 0b00000100
#define FLAG_CONSTANT_PITCH 0b00001000
#define FLAG_HIDDEN 0b00010000

// Generators
#define GENERATOR_SQUARE 0
#define GENERATOR_SAW 1
#define GENERATOR_SINE 2
#define GENERATOR_WAVETABLE 3
#define GENERATOR_NOISE 4
#define GENERATOR_COUNT 5

// Effects
#define EFFECT_GAINER 0
#define EFFECT_DISTORTION 1
#define EFFECT_FILTER 2
#define EFFECT_DELAY 3
#define EFFECT_COUNT 4

// Commands
#define INSTRUCTION_EMPTY 0
#define INSTRUCTION_PORTAMENTO_UP 1
#define INSTRUCTION_PORTAMENTO_DOWN 2
#define INSTRUCTION_SET_MASTER_GAINER 3
#define INSTRUCTION_SET_BPM 4
#define INSTRUCTION_SET_DIVISION 5
#define INSTRUCTION_CHANGE_FLOAT_VALUE 6
#define INSTRUCTION_CHANGE_BYTE_VALUE 7
#define INSTRUCTION_CHANGE_WORD_VALUE 8
#define INSTRUCTION_CHANGE_DWORD_VALUE 9
#define INSTRUCTION_ADD_FLOAT_VALUE 10
#define INSTRUCTION_ADD_BYTE_VALUE 11
#define INSTRUCTION_ADD_WORD_VALUE 12
#define INSTRUCTION_ADD_DWORD_VALUE 13
#define INSTRUCTION_COUNT 14

// Oscillators
#define BASE_VOLUME 0x8000

// Noise
#define NOISE_SEED 0xACE1
#define NOISE_GALOIS_GENERATOR 0xB400
