#define TRACKER

#define SIZE_CHANNEL 16
#define SIZE_ENVELOPE 14

#define SIZE_OSCILLATOR_SINE 1
#define SIZE_OSCILLATOR_SQUARE 2
#define SIZE_OSCILLATOR_SAW 2
#define SIZE_OSCILLATOR_WAVETABLE 3
#define SIZE_OSCILLATOR_NOISE 1

#define SIZE_DSP 11
#define SIZE_DSP_GAINER 11
#define SIZE_DSP_DISTORTION 11
#define SIZE_DSP_FILTER 11
#define SIZE_DSP_DELAY 15

#define SIZE_COMMAND 2
#define SIZE_COMMAND_PORTAMENTO_UP 5
#define SIZE_COMMAND_PORTAMENTO_DOWN 5
#define SIZE_COMMAND_SET_MASTER_GAINER 4
#define SIZE_COMMAND_SET_BPM 4
#define SIZE_COMMAND_SET_DIVISION 3
#define SIZE_COMMAND_CHANGE_BYTE_VALUE 5
#define SIZE_COMMAND_CHANGE_WORD_VALUE 6
#define SIZE_COMMAND_CHANGE_DWORD_VALUE 8
#define SIZE_COMMAND_CHANGE_FLOAT_VALUE 8

#define SIZE_COMMANDS_CHANNEL 2
