; File automatically generated by config.py
    %define SAMPLE_RATE 29102
    %define PRECALCULATE 0

    %define TABLE_SIZE 1024
    %define ANGLE_CONSTANT __float32__(0.006135923151542565)

    %define DIRECT_MODE 0
    %define SB_BUFFER_SIZE 1024
    %define SB_EXACT_SAMPLE_RATE 0
    %define SB_BASE_PORT 0x220
    %define SB_IRQ 7
    %define SB_8BIT 0
    %define SB_16BIT 1

    %define FFT 1
    %define FFT_SIZE 16
    %define FFT_ANGLE_CONSTANT 0.39269908169872414
