; Envelope
    %define ENVELOPE_SIZE 12
    %define ENVELOPE_BASE_VOLUME 0
    %define ENVELOPE_SUSTAIN_LEVEL 2
    %define ENVELOPE_ATTACK 4

; Sequence
    %define SEQUENCE_NOTES 1

; Instrument
    %define INSTRUMENT_SIZE 6
    %define INSTRUMENT_ENVELOPE_INDEX 0
    %define INSTRUMENT_ENVELOPE_MODE 1
    %define INSTRUMENT_SEQUENCE_INDEX 2
    %define INSTRUMENT_SEQUENCE_CURRENT_NOTE 3
    %define INSTRUMENT_OSCILLATOR_INDEX 4
    %define INSTRUMENT_TRANSPOSE 5
