; Envelope
    %define ENVELOPE_SIZE 12
    %define ENVELOPE_BASE_VOLUME 0
    %define ENVELOPE_SUSTAIN_LEVEL 2
    %define ENVELOPE_ATTACK 4

; Sequence
    %define SEQUENCE_NOTES 1

; Instrument
    %define INSTRUMENT_SIZE 25

    %define INSTRUMENT_ENVELOPE_INDEX 0
    %define INSTRUMENT_ENVELOPE_MODE 1
    %define INSTRUMENT_ENVELOPE_TIMER 2

    %define INSTRUMENT_SEQUENCE_INDEX 6
    %define INSTRUMENT_SEQUENCE_REMAINING_TICKS 7
    %define INSTRUMENT_SEQUENCE_CURRENT_NOTE 11
