    %include "src/elements/osc.asm"
    %include "src/elements/adsr.asm"
    %include "src/elements/sequence.asm"
    %include "src/elements/order.asm"
    %include "src/elements/channel.asm"
    %include "src/elements/dsp.asm"
    %include "src/elements/mixer.asm"
